package app.figma.api.v1.dto;

public enum NodeType {
    BOOLEAN, BOOLEAN_OPERATION, CANVAS, COMPONENT, DOCUMENT, ELLIPSE, FRAME, GROUP, INSTANCE, LINE, RECTANGLE, REGULAR_POLYGON, SLICE, STAR, TEXT, VECTOR;
}
